version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Prepare reports directories
          command: mkdir -p ~/test-results/{pytest,flake8}

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Run tests & lint
          command: |
            pip install -U --user pip setuptools tox flake8_junit_report
            # tox -epy35 -- --junitxml=~/test-results/pytest/py35.xml
            # tox -eflake8_ci |& flake8_junit flake8.txt ~/test-results/flake8/flake8.xml
            tox -epy35,flake8_ci

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "src/requirements.txt" }}

      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results
